export const CONFIG = {
  REDIS_HOST: process.env.REDIS_HOST || '127.0.0.1',
  REDIS_HOST_PORT: Number(process.env.REDIS_HOST_PORT) || 6379,
  REDIS_CONNECT_TIMEOUT: Number(process.env.REDIS_CONNECT_TIMEOUT) || 10000,
  IS_LOCAL_ENVIRONMENT: process.env.NODE_ENV !== 'production',
  WHATSAPP_SYSTEM_TOKEN: process.env.WHATSAPP_SYSTEM_TOKEN,
  WHATSAPP_PHONE_NUMBER_ID: process.env.WHATSAPP_PHONE_NUMBER_ID,
  UISP_API_BASE_URL: process.env.UISP_API_BASE_URL,
  UISP_API_KEY: process.env.UISP_API_KEY,
  NODE_ENV: process.env.NODE_ENV,
  CRON_TRIGGER_TOKEN: process.env.CRON_TRIGGER_TOKEN,
  DEV_TEST_RECEIVER_NUMBER: process.env.DEV_TEST_RECEIVER_NUMBER,
}; 